### ISSUE TITLE
Feature to only shutdown if server is empty

### ISSUE THREAD

**Issue by guilhermevleite** [coolsimulations/ServerStop#3]
This is a suggestion to a feature that would delay the shutdown if the server has people online.

**Comment by coolsimulations** [comment]
Definitely an option I will put in the config file in the next version. There are a few changes now people have requested for ServerStop but it's not a mod that I give priority to so it's not gonna come out anytime soon.

**Comment by coolsimulations** [comment]
Actually, I just added it in, along with some other new features in https://github.com/coolsimulations/ServerStop/commit/17c698478ccd12e5fbdb3e2fb8cf5bb05d927c24. The update will be out when Forge 1.17 is out.
